List<String> genders = [
  'Male',
  'Female',
];

List<String> colors = [
  'Aqua',
  'Beige',
  'Black',
  'Afro-Chausie',
  'Blue',
  'Bluish Gray',
  'Brown',
  'Copper',
  'Cyan',
  'Dark Blue',
  'Dark Brown',
  'Dark Gray',
  'Dark Green',
  'Dark Orange',
  'Dark Purple',
  'Dark Red',
  'Dark Yellow',
  'Ginger',
  'Golden',
  'Golden Brown',
  'Golden Yellow',
  'Gray',
  'Green',
  'Indigo',
  'Light Blue',
  'Light Brown',
  'Light Gray',
  'Light Green',
  'Light Orange',
  'Light Pink',
  'Light Purple',
  'Light Red',
  'Light Yellow',
  'Lilac',
  'Magenta',
  'Orange',
  'Pink',
  'Purple',
  'Red',
  'Scarlet',
  'Silver',
  'Tan',
  'Turquoise',
  'Violet',
  'White',
  'Yellow',
  'None',
];
